language: objective-c
osx_image: xcode9
script:
    - xcodebuild clean test -project greenthumb.xcodeproj -scheme greenthumb -destination platform=iOS Simulator,name=iPhone 8,OS=11.3.1 CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO

